'''
The kernel of generation of data (Polars + Numpy & DL)
'''
import polars as pl
import numpy as np
# import pytorch as PT #Install this shit later


def generate_data(params: dict) -> pl.DataFrame:
    '''
    General data generation function. It consists of two parts: normal data and fraud data
    that is generated by another function 'generate_fraud_data'
    '''

    fraud_data = generate_fraud_data(params=params)

    return normal_data + fraud_data

def generate_fraud_data(params: dict) -> pl.DataFrame:
    '''
    Fraud data generation function. There are 3 params that can help to recognise fraud data:
    - a lot of small transactions in a short period of time
    - unusual time of transaction (between certain hours, e.g. 12:00 pm - 06:00 am)
    - a huge amount transactioned in once
    '''

    return fraud


